config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#welcome'
  resources :users

  get 'welcome', to: 'sessions#welcome'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'authorized', to: 'sessions#page_requires_login'
  get '/sessions/new', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/search' => 'users#search', :as => 'search_page'
 


  get 'close_contacts', to: 'close_contacts#index'
  get 'close_contacts/new', to: 'close_contacts#new'
  post 'close_contacts/new', to: 'close_contacts#create'

  resources :testforms
  resources :close_contacts

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/close_contact.rb
class CloseContact < ApplicationRecord
  belongs_to :user

  validates :name, presence:true
  
end

app/models/testform.rb
class Testform < ApplicationRecord
  belongs_to :user

  validates :date, presence:true

  RESULT = ["Positive", "Negative"]

  validates :RESULT, presence:true
  
end

app/models/user.rb
class User < ApplicationRecord
    
    validates :cellphone, presence:true
    validates :first_name, presence:true
    validates :last_name, presence:true
    validates :email, presence:true
    validates :username, presence:true, uniqueness: {case_sensitive: false}
    
    has_secure_password

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :authorized
    helper_method :current_user
    helper_method :logged_in?
    #helper_method :signed_up?
    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end
    
    #def signed_up?
    #    User.new?
    #end

    def authorized
        redirect_to'/welcome' unless logged_in?        
    end
end

app/controllers/close_contacts_controller.rb
class CloseContactsController < ApplicationController
    def create
        @close_contact = CloseContact.new(close_contact_params)
        @close_contact.user_id = current_user.id
        respond_to do |format|
            if @close_contact.save
                format.html {redirect_to @close_contact, notice: 'Close contact was added successfully'}
                format.json {render :show, status: :created, location: @close_contact}
            else
                format.html { render :new}
                format.json { render json: @close_contact.errors, status: :unprocessable_entity}
            end
        end
    end

    def index
        @close_contact = CloseContact.all
    end

    def show
        @close_contact = CloseContact.find(params[:id])
    end

    def new
        @close_contact = CloseContact.new
    end

    def destroy
        @close_contact = CloseContact.find(params[:id])
        @close_contact.destroy
        respond_to do |format|
            format.html { redirect_to close_contacts_url, notice: 'Close contact was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    def set_close_contact
        @close_contact = CloseContact.find(params[:id])
    end

    def close_contact_params
        params.require(:close_contact).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized,only: [:new, :create, :welcome]
  def new
  end
  
  def login
  end
  
  def create
    @user =User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id]= @user.id
      redirect_to '/welcome'
    else
      redirect_to '/login', notice: "Incorrect password"
    end
  end

  def page_requires_login
  end

  def destroy
    session.delete(:user_id)
    @current_user=nil
    
    redirect_to '/welcome', notice: "User was successfully logged out"
  end
 

  def welcome
  end
end

app/controllers/testforms_controller.rb
class TestformsController < ApplicationController

    def create
        @testform = Testform.new(testform_params)
        @testform.user_id = current_user.id
        respond_to do |format|
            if @testform.save
                format.html {redirect_to @testform, notice: 'Testform was created successfully'}
                format.json {render :show, status: :created, location: @testform}
            else
                format.html { render :new}
                format.json { render json: @testform.errors, status: :unprocessable_entity}
            end
        end
    end

    def index
        @testform = Testform.all
    end

    def show
        @testform = Testform.find(params[:id])
    end

    def new
        @testform = Testform.new
    end

    private

    def set_testform
        @testform = Testform.find(params[:id])
    end

    def testform_params
        params.require(:testform).permit(:date, :RESULT)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users= User.all
  end

  def search
    if params[:search].blank?
        redirect_to(root_path, alert: "Empty field!") and return
    else
      @parameter= params[:search].downcase
      @results=User.all.where("lower(cellphone) LIKE :search", search: "%#{@parameter}%")
    end
  end
  

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to '/welcome', notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:cellphone, :first_name, :last_name, :email, :username, :password, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/close_contact_helper.rb
module CloseContactHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/testform_helper.rb
module TestformHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/close_contacts/_form.html.erb
<%= form_with(model: close_contact, local: true) do |form| %>
    <% if close_contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(close_contact.errors.count, "error") %> prohibited this close contact from being saved:</h2>
  
        <ul>
          <% close_contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <%= form.submit %>
<% end %>

app/views/close_contacts/index.html.erb
<p id ="notice"><%= notice %></p>

<h1>Close Contacts</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>

    <tbody>
        <% @close_contact.each do |close_contact| %>
            <tr>
                <td><%= close_contact.name %></td>
                <td><%= link_to 'Destroy', close_contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'Submit New Close Contact', "/close_contacts/new" %>

app/views/close_contacts/new.html.erb
<h1>New Close Contact</h1>

<%= render 'form', close_contact: @close_contact %>

<%= link_to 'Back', close_contacts_path %>

app/views/close_contacts/show.html.erb
<h1>Add a new close contact</h1>

<p>
    <strong>Name:</strong>
    <%= @close_contact.name %>
</p>

<%= link_to 'Back', '/close_contacts' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tracer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/testforms/_form.html.erb
<%= form_with(model: testform, local: true) do |form| %>
    <% if testform.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(testform.errors.count, "error") %> prohibited this testform from being saved:</h2>
  
        <ul>
          <% testform.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :date %>
      <%= form.text_field :date %>
    </div>
  
    <div class="field">
            <%= form.label :result %>
            <%= form.select :RESULT, Testform::RESULT %>
    </div>

    <%= form.submit %>
<% end %>
    

app/views/testforms/index.html.erb
<p id ="notice"><%= notice %></p>

<h1>Testform</h1>

<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Result</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @testform.each do |testform| %>
            <tr>
                <td><%= testform.date %></td>
                <td><%= testform.RESULT %></td>
                <td><%= link_to 'Show', testform %></td> 
            </tr>
        <% end %>
    </tbody>
</table>

<br>

<li><%= link_to 'Submit New Test Result', "/testforms/new" %></li>

app/views/testforms/new.html.erb
<h1>New Test Result</h1>

<%= render 'form', testform: @testform %>


<li><%= link_to 'Back', testforms_path %></li>

app/views/testforms/show.html.erb
<h1>Added a new test result</h1>

<p>
    <strong>Date:</strong>
    <%= @testform.date %>
</p>

<p>
    <strong>Result:</strong>
    <%= @testform.RESULT %>
</p>

<li><%= link_to 'Back', '/testforms' %></li>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :cellphone %>
    <%= form.text_field :cellphone %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>


<table>
    <thead>
        <tr>
            <th>Cellphone</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.cellphone %></td>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.email %></td>

            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<br>
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/search.html.erb
<h3>Search Result </h3>
<table>
    <thead>
        <tr>
            <th>Cellphone</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @results.each do |result| %>
        <tr>
            <td><%= result.cellphone %></td>
            <td><%= result.first_name %></td>
            <td><%= result.last_name %></td>
            <td><%= result.email %></td>

            <td><%= link_to 'Show', result %></td>
            <td><%= link_to 'Edit', edit_user_path(result) %></td>
            <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<br>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cellphone:</strong>
  <%= @user.cellphone %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>